### ISSUE TITLE
Using custom dataset

### ISSUE THREAD

**Issue by sharmrit** [DekuLiuTesla/CityGaussian#2] opened 2024-08-07 16:04 UTC
Your work is truly impressive. It would be great if you could share instruction on how to use custom dataset. For example, I record a video using drone and then want to use your technique for large scale 3D reconstruction of a scene.

**Comment by nurbanu170399** [comment] 2024-08-07 16:43
Same here. Struggling with adapting my own dataset. the scripts, the config folder and the data structure is confusing.

**Comment by DekuLiuTesla** [comment] 2024-08-12 05:39
Hi, sorry for the confusing custom dataset usage. I'm planning to add a detailed instruction in repo. I have provided some advice at https://github.com/DekuLiuTesla/CityGaussian/issues/3#issuecomment-2283141338. Since the issue is similar, I would close this issue. If you have any other questions about this custom dataset usage, don't hesitate to comment in https://github.com/DekuLiuTesla/CityGaussian/issues/3.

**Closed by DekuLiuTesla** 2024-08-12 05:39 UTC
